FROM mhart/alpine-node:12

# add dependencies
RUN apk add --no-cache git

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install app dependencies
COPY package.json /usr/src/app/
RUN yarn install

# bundle app source
COPY . /usr/src/app

CMD ["yarn", "build"]
